services:
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "8082:80"
    depends_on:
      init:
        condition: service_completed_successfully
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks: [appnet]

  init:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:delegated
      - vendor:/var/www/html/vendor
      - node_modules:/var/www/html/node_modules
    command: sh -lc "
      composer install &&
      npm install
      "
    restart: "no"

  app:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    working_dir: /var/www/html
    depends_on:
      init:
        condition: service_completed_successfully
      mysql:
        condition: service_started
    networks: [appnet]

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: hytale
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      init:
        condition: service_completed_successfully
    volumes:
      - mysql_data:/var/lib/mysql
    networks: [ appnet ]

volumes:
  mysql_data:
  vendor:
  node_modules:

networks:
  appnet:
    driver: bridge
